# Data Structures, Functions, NumPy & Pandas

---

## Section A: Data Structures & Control Structures

### Question 1: List Operations

In [ ]:
# Question 1: List of 5 integers and common list operations

my_list = [10, 30, 20, 40, 50]
print("Original list:", my_list)

# append – adds a single element to the end
my_list.append(60)
print("After append(60):", my_list)

# extend – adds multiple elements from another iterable
my_list.extend([70, 80])
print("After extend([70, 80]):", my_list)

# insert – inserts element at a specified index
my_list.insert(2, 99)
print("After insert(2, 99):", my_list)

# remove – removes first occurrence of a value
my_list.remove(99)
print("After remove(99):", my_list)

# pop – removes and returns element at given index (default: last)
popped = my_list.pop(0)
print(f"After pop(0): {my_list}  | Popped value: {popped}")

# index – returns index of first occurrence of value
print("Index of 40:", my_list.index(40))

# count – counts occurrences of a value
my_list.append(20)
print("Count of 20:", my_list.count(20))

# sort – sorts list in ascending order (in-place)
my_list.sort()
print("After sort():", my_list)

# reverse – reverses the list in-place
my_list.reverse()
print("After reverse():", my_list)

# clear – removes all elements
my_list.clear()
print("After clear():", my_list)

Original list: [10, 30, 20, 40, 50]
After append(60): [10, 30, 20, 40, 50, 60]
After extend([70, 80]): [10, 30, 20, 40, 50, 60, 70, 80]
After insert(2, 99): [10, 30, 99, 20, 40, 50, 60, 70, 80]
After remove(99): [10, 30, 20, 40, 50, 60, 70, 80]
After pop(0): [30, 20, 40, 50, 60, 70, 80]  | Popped value: 10
Index of 40: 2
Count of 20: 2
After sort(): [20, 20, 30, 40, 50, 60, 70, 80]
After reverse(): [80, 70, 60, 50, 40, 30, 20, 20]
After clear(): []


### Question 2: Tuple Immutability

In [ ]:
# Question 2: Tuple of 3 student names

students = ("Alice", "Bob", "Charlie")
print("Tuple:", students)

# Attempting to change the second name
try:
    students[1] = "David"
except TypeError as e:
    print(f"Error: {e}")

print()
print("Explanation:")
print("Tuples are IMMUTABLE in Python.")
print("Once created, their elements cannot be modified, added, or removed.")
print("This is by design — tuples are used for fixed collections of data.")

Tuple: ('Alice', 'Bob', 'Charlie')
Error: 'tuple' object does not support item assignment

Explanation:
Tuples are IMMUTABLE in Python.
Once created, their elements cannot be modified, added, or removed.
This is by design — tuples are used for fixed collections of data.


### Question 3: Set with Duplicates

In [ ]:
# Question 3: Set with duplicate values

raw = {1, 2, 2, 3, 4, 4, 4, 5}
print("Set:", raw)

print()
print("Explanation:")
print("A set automatically removes duplicate values.")
print("Sets store only UNIQUE elements — each value appears at most once.")
print("Sets are also unordered, so the printed order may differ from insertion order.")

Set: {1, 2, 3, 4, 5}

Explanation:
A set automatically removes duplicate values.
Sets store only UNIQUE elements — each value appears at most once.
Sets are also unordered, so the printed order may differ from insertion order.


### Question 4: Dictionary Operations

In [ ]:
# Question 4: Dictionary with update and new key

person = {
    "name": "Riya",
    "age" : 22,
    "city": "Hyderabad"
}
print("Original dictionary:", person)

# Update age
person["age"] = 23
print("After updating age:", person)

# Add a new key 'email'
person["email"] = "riya@example.com"
print("After adding email:", person)

Original dictionary: {'name': 'Riya', 'age': 22, 'city': 'Hyderabad'}
After updating age: {'name': 'Riya', 'age': 23, 'city': 'Hyderabad'}
After adding email: {'name': 'Riya', 'age': 23, 'city': 'Hyderabad', 'email': 'riya@example.com'}


### Question 5: Voting Eligibility

In [ ]:
# Question 5: Check voting eligibility

age = 20   # Change this value to test different cases

if age >= 18:
    print(f"Age {age}: You are eligible to vote.")
else:
    print(f"Age {age}: You are NOT eligible to vote yet.")

# Test with a minor
age = 15
if age >= 18:
    print(f"Age {age}: You are eligible to vote.")
else:
    print(f"Age {age}: You are NOT eligible to vote yet.")

Age 20: You are eligible to vote.
Age 15: You are NOT eligible to vote yet.


### Question 6: Grade Classification

In [ ]:
# Question 6: Print grade based on marks

def get_grade(marks):
    """Returns the grade for a given marks value."""
    if marks >= 90:
        return "A"
    elif marks >= 75:
        return "B"
    elif marks >= 50:
        return "C"
    else:
        return "Fail"

# Test with multiple values
for marks in [95, 82, 63, 45]:
    print(f"Marks: {marks}  →  Grade: {get_grade(marks)}")

Marks: 95  →  Grade: A
Marks: 82  →  Grade: B
Marks: 63  →  Grade: C
Marks: 45  →  Grade: Fail


### Question 7: Positive / Even / Zero / Negative Check

In [ ]:
# Question 7: Check if a number is positive, zero, or negative;
#              and if positive, whether it is also even.

def classify_number(n):
    """Classifies a number as positive/negative/zero and even/odd."""
    if n > 0:
        if n % 2 == 0:
            print(f"{n} is positive and even.")
        else:
            print(f"{n} is positive and odd.")
    elif n == 0:
        print(f"{n} is zero.")
    else:
        print(f"{n} is negative.")

# Test cases
for num in [8, 7, 0, -3]:
    classify_number(num)

8 is positive and even.
7 is positive and odd.
0 is zero.
-3 is negative.


---
## Section B: NumPy

### Question 8: Scalar, 1D and 2D NumPy Arrays

In [ ]:
import numpy as np

# Scalar – 0-dimensional array
scalar = np.array(5)
print("Scalar:", scalar, "| ndim:", scalar.ndim, "| shape:", scalar.shape)

# 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("
1D Array:", arr_1d, "| ndim:", arr_1d.ndim, "| shape:", arr_1d.shape)

# 2D array (2x3) with values 10, 20, ..., 60
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("
2D Array (2x3):")
print(arr_2d)
print("ndim:", arr_2d.ndim, "| shape:", arr_2d.shape)

Scalar: 5 | ndim: 0 | shape: ()

1D Array: [1 2 3 4 5] | ndim: 1 | shape: (5,)

2D Array (2x3):
[[10 20 30]
 [40 50 60]]
ndim: 2 | shape: (2, 3)


### Question 9: 4×4 Random Integer Array

In [ ]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
np.random.seed(42)   # seed for reproducibility
rand_arr = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Integer Array (0–100):")
print(rand_arr)
print("
Shape:", rand_arr.shape)
print("Min:", rand_arr.min(), "| Max:", rand_arr.max(), "| Mean:", rand_arr.mean().round(2))

4x4 Random Integer Array (0–100):
[[51 92 14 71]
 [60 20 82 86]
 [74 74 87 99]
 [23  2 21 52]]

Shape: (4, 4)
Min: 2 | Max: 99 | Mean: 57.38


### Question 10: 2D NumPy Array → Pandas DataFrame

In [ ]:
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
np_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("NumPy Array:")
print(np_array)

# Convert to DataFrame and add column names
df = pd.DataFrame(np_array, columns=["A", "B", "C"])

print("
Pandas DataFrame:")
print(df)
print("
Data types:")
print(df.dtypes)

NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Pandas DataFrame:
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Data types:
A    int64
B    int64
C    int64
dtype: object


---
## Section C: Exploring Pandas

### Question 11: DataFrame Operations

In [ ]:
import pandas as pd
import numpy as np

# Create a DataFrame with 10 rows manually
data = {
    "Name"  : ["Aarav", "Bhavna", "Chetan", "Deepa", "Eshan",
                "Farida", "Gaurav", "Heena", "Ishan", "Jasmine"],
    "Age"   : [23, 28, 35, 29, 22, 31, 27, 24, 30, 26],
    "City"  : ["Hyderabad", "Mumbai", "Delhi", "Pune", "Chennai",
                "Bangalore", "Hyderabad", "Mumbai", "Delhi", "Pune"],
    "Salary": [45000, 62000, 75000, None, 38000, 80000, 55000, 47000, None, 69000]
}

df = pd.DataFrame(data)
print("=" * 45)
print("Original DataFrame:")
print("=" * 45)
print(df)

Original DataFrame:
      Name  Age       City   Salary
0    Aarav   23  Hyderabad  45000.0
1   Bhavna   28     Mumbai  62000.0
2   Chetan   35      Delhi  75000.0
3    Deepa   29       Pune      NaN
4    Eshan   22    Chennai  38000.0
5   Farida   31  Bangalore  80000.0
6   Gaurav   27  Hyderabad  55000.0
7    Heena   24     Mumbai  47000.0
8    Ishan   30      Delhi      NaN
9  Jasmine   26       Pune  69000.0


In [ ]:
# .info() – column types and non-null counts
print(".info():")
df.info()

.info():


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [ ]:
# .describe() – summary statistics for numeric columns
print("
.describe():")
print(df.describe().round(2))


.describe():
        Age        Salary
count  10.00       8.000
mean   27.50   58875.000
std     3.69   13758.620
min    22.00   38000.000
25%    24.75   46750.000
50%    27.50   58500.000
75%    30.25   68250.000
max    35.00   80000.000


In [ ]:
# Select 'Name' and 'City' columns
print("Selected columns – Name & City:")
print(df[["Name", "City"]])

Selected columns – Name & City:
      Name       City
0    Aarav  Hyderabad
1   Bhavna     Mumbai
2   Chetan      Delhi
3    Deepa       Pune
4    Eshan    Chennai
5   Farida  Bangalore
6   Gaurav  Hyderabad
7    Heena     Mumbai
8    Ishan      Delhi
9  Jasmine       Pune


In [ ]:
# Drop 'City' column
df_no_city = df.drop(columns=["City"])
print("After dropping City column:")
print(df_no_city)

After dropping City column:
      Name  Age   Salary
0    Aarav   23  45000.0
1   Bhavna   28  62000.0
2   Chetan   35  75000.0
3    Deepa   29      NaN
4    Eshan   22  38000.0
5   Farida   31  80000.0
6   Gaurav   27  55000.0
7    Heena   24  47000.0
8    Ishan   30      NaN
9  Jasmine   26  69000.0


In [ ]:
# Fill missing Salary values with the mean
salary_mean = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(salary_mean)
print(f"Mean salary used for imputation: {salary_mean:.2f}")
print("
After filling missing Salary values:")
print(df)
print("
Remaining missing values:", df.isnull().sum().sum())

Mean salary used for imputation: 58875.00

After filling missing Salary values:
      Name  Age       City    Salary
0    Aarav   23  Hyderabad  45000.00
1   Bhavna   28     Mumbai  62000.00
2   Chetan   35      Delhi  75000.00
3    Deepa   29       Pune  58875.00
4    Eshan   22    Chennai  38000.00
5   Farida   31  Bangalore  80000.00
6   Gaurav   27  Hyderabad  55000.00
7    Heena   24     Mumbai  47000.00
8    Ishan   30      Delhi  58875.00
9  Jasmine   26       Pune  69000.00

Remaining missing values: 0


In [ ]:
# Remove duplicate rows
df_clean = df.drop_duplicates()
print(f"Rows before drop_duplicates: {len(df)}")
print(f"Rows after  drop_duplicates: {len(df_clean)}")
print("
Final clean DataFrame:")
print(df_clean)

Rows before drop_duplicates: 10
Rows after  drop_duplicates: 10

Final clean DataFrame:
      Name  Age       City    Salary
0    Aarav   23  Hyderabad  45000.00
1   Bhavna   28     Mumbai  62000.00
2   Chetan   35      Delhi  75000.00
3    Deepa   29       Pune  58875.00
4    Eshan   22    Chennai  38000.00
5   Farida   31  Bangalore  80000.00
6   Gaurav   27  Hyderabad  55000.00
7    Heena   24     Mumbai  47000.00
8    Ishan   30      Delhi  58875.00
9  Jasmine   26       Pune  69000.00
